InjectHtml._encode = function(obj) {
	//Convert the given keyed object into a single string, wrapping each HTML block with comments to include the name of the block 
	return obj && typeof obj == 'object' && 
		Object.keys(obj).map(function(key) {
			return '\n' +
				'<!--start-' + key + '-->' +
				//TODO: Probably want to add some checks/HTML-escaping for special characters (it's generated by the server so should be trusted and sanitised mostly by SSR anyway)
				obj[key] +
				'<!--end-' + key + '-->';
		}
	).join('');
};

//This is pretty much redundant, but might revisit if anyone thinks it'd be useful.
InjectHtml._decode = function(str) {
	var arr = str.split(/\n?<!--start-.*/);
	//console.log('decoding rendered html set from', str);
	//TODO: This needs a bit of work
	var obj = {};
	arr.forEach(function(pos, frag) {
		var parts = frag.match(/(^.*?)-->(.*?)<!--end-(.*?)-->/gim);
		var key = parts[0] == parts[2] ? parts[0] : false;
		if(key) {
			obj[key] = parts[1];
		} else {
			console.warn('Could not decode key for fragement', parts, 'from', frag);
		}
	});
	return obj;
};
